spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true